version: "3"
services:
  mongo:
    image: mongo
    container_name: jizhang-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    restart: always