###
GET http://localhost:5000/api/test/hello


###
GET http://localhost:5000/api/test/hello/redis


###
GET http://localhost:5000/api/test/hello/cacheService


###
GET http://localhost:5000/api/test/hello/list


###
POST http://localhost:5000/api/test/hello/post
Content-Type: application/json

{
  "name": "sfdd",
  "sex": "w233",
  "age": "233",
  "id": 0,
  "money": 0.0,
  "birthday": "2023-08-12"
}


###
POST http://localhost:5000/api/test/hello/pageQuery
Content-Type: application/json

{
  "pageIndex": 0,
  "pageSize": 2
}